#!/bin/bash

LABEL="${LABEL:-CPU}"
USAGE_INTERVAL=${USAGE_INTERVAL:-30}

CRIT_THRESHOLD=${CRIT_THRESHOLD:-80}
CRIT_COLOR=${CRIT_COLOR:-#EF0000}

WARN_THRESHOLD=${WARN_THRESHOLD:-50}
WARN_COLOR=${WARN_COLOR:-#FFDD00}

print_block() {
    local color=""

    if (( $(echo "$1 > $CRIT_THRESHOLD" | bc -l) )); then
        color=$CRIT_COLOR
    elif (( $(echo "$1 > $WARN_THRESHOLD" | bc -l) )); then
        color=$WARN_COLOR
    fi   
    

    printf '{"full_text": "%s %s%%", "color": "%s"}\n' $LABEL $1 $color
}

print_block "-.--"

while : ; do
    CPU_USAGE="$(mpstat 1 1 | awk '{print $3}' | xargs | awk '{print $3}' | sed 's/,/./')"
    print_block $CPU_USAGE
    sleep $USAGE_INTERVAL
done
